trigger:
  branches:
    include:
      - main  # Build on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu agent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'  # Install Node.js 14.x

  - script: |
      npm install  # Install dependencies
      npm run build  # Build the React application
    displayName: 'Install dependencies and build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/build'  # Path to build output directory
      artifactName: 'frontend-artifact'  # Name of the artifact to publish
    displayName: 'Publish Artifact'  # Publish build artifact
